"""Script with the GUI text in CATALAN.
sectionauthor:: Artur Martí Gelonch <artur.marti@students.salle.url.edu>
"""

class LangENG:
    def __init__(self):
        #BASICS
        self.YES = "Yes"
        self.NO = "No"
        self.OK = "Ok"
        self.ACCEPT = "Accept"
        self.CANCEL = "Cancel"
        self.CONTINUE = "Continue"
        self.SAVE = "Save"
        self.BACK = "Back"
        # MENU
        self.LANG = "Language"

        # MAIN PAGE
        self.MAIN_TITLE = "Pressure Injuries Image Annotation"
        self.BUTTON_1 = "Add images to database"
        self.BUTTON_2 = "Consult database"

        # PROCESSING PAGE
        self.TITLE_PROCESSING = self.BUTTON_1
        self.IMAGE_LOAD = "Load image"
        self.IMAGE_PROCESSING = "Process image"

        self.META_TITLE = "Data collection"
        self.META_DATA_FILL = "Fill the following fields:"
        self.META_CODE = "Code"
        self.META_CHECK = "Check"
        self.META_YEAR = "Birth year"
        self.META_SEX = "Gender"
        self.META_MAN = "Male"
        self.META_WOMAN = "Female"
        self.META_OTHER = "Other"
        self.META_IMMOBILIZATION = "Immobilization time"
        self.META_DAYS = "Days"
        self.META_WEEKS = "Weeks"
        self.META_MONTHS = "Months"
        self.META_HOSPITALIZATION = "Hospitalization time"
        self.META_INST = "Institutionalization time"
        self.META_DATE = "Date"
        self.META_EMINA = "Emina"
        self.META_BARTHEL = "Barthel Index"
        self.META_CALCULATE = "Calculate"
        self.META_CONTENTION = "Mechanical contention"
        self.META_GRADE = "Injury's grade"
        self.META_EXO = "Exsudate culture"
        self.META_POSITIVE = "Positive"
        self.META_NEGATIVE = "Negative"
        self.META_PROTEIN = "Total protein"
        self.META_ALB = "Albumin"
        self.META_TREATMENT = "Treatment"
        self.META_ANTIBIOTIC = "Antibiotics"
        self.META_TOPIC = "Topic"
        self.META_SAVE = "Save"
        self.META_EMPTY_CODE = "Write code to validate"

        self.CODE_ERROR = "Code must contain 4 digits"
        self.AGE_RROR = "Birth year must have 4 enters"
        self.N_IMM_ERROR = "Invalid format: immobilization time"
        self.H_HOSP_ERROR = "Invalid format: hospitalization time"
        self.N_INST_ERROR = "Invalid format: institutionalization time"
        self.DATE_ERROR = "Invalid format: date"
        self.N_CONTEN_ERROR = "Invalid format: mechanical contention"

        #PRE SEGMENTATION GUI
        self.PRE_CONFIRM_REGION = "Confirm region"
        self.PRE_CORRECT_REGION = "Is the selected region OK?"

        self.PRE_NEW_CODE_TITLE = "New patient"
        self.PRE_NEW_CODE_DESC_1 = "A new patient will be registered."
        self.PRE_LABEL_OLD = "Injury localization:"
        self.PRE_NEW_LOCATION_EMPTY = "Field must be filled: localization."

        self.PRE_ASK_CODE_TITLE = "Registered patient"
        self.PRE_ASK_CODE_DESC_1 = "Select option:"
        self.PRE_RADIOBUTTON_OLD = "Add image from a registered injury."
        self.PRE_RADIOBUTTON_NEW = "Register new injury."
        self.PRE_LABEL_NEW = "Localization:"
        self.PRE_CODE_RADIOBUTTONS = "Select an option"

        self.PRE_LOCATION_REPEATED = "Localization repeated. It must be different."

        # SEGMENTATION GUI
        # Surce: https://www.woundsource.com/blog/identifying-types-tissues-found-pressure-ulcers
        self.HELPER_GRANULATION = "Granulation tissue often appears as red, bumpy tissue that is described as “cobblestone-like” in appearance."
        self.HELPER_NECROSIS = "Necrosis tissue is black or brown, composed of dead granulation tissue, muscle, fat, tendon or skin."
        self.HELPER_SLOUGH = "Slough can be identified as a stringy white/yellow/green/brown mass that may or may not be firmly attached to surrounding tissue."
        self.SEG_TITLE = "Segmentation tool"
        self.SEG_DESC = "Select the total perimeter and the different tissues from the injury:"
        self.SEG_WHITE = "Whitebalance"
        self.SEG_PERIMETER = "Perimeter"
        self.SEG_GRANULATION = "Granulation"
        self.SEG_NECROSIS = "Necrosis"
        self.SEG_SLOUGH = "Slough"
        self.SEG_WHITEBALANCE_DESC = "Tool under development, supervision required."
        self.SEG_PERIMETER_DESC = "Select the total perimeter of the injury"
        self.SEG_SELECTED_ZONES = "Selected zones: "
        self.SEG_GRANULATION_EX = "Example Granulation"
        self.SEG_NECROSIS_EX = "Example Necrosis"
        self.SEG_SLOUGH_EX = "Example Slough"
        self.SEG_CONFIRM_WB = "Confirm white balance"

        # MODEL PRESSURE IMAGE
        self.MODEL_PRESSURE_IMG = "Select rectangular shape: Target + Injury. ENTER to accept."

        #EMINA-BARTHEL
        self.EB_WINDOW_B = "Calculate Barthel index"
        self.EB_WINDOW_E = "Calculate Emina index"
        # Source: (https://ca.wikipedia.org/wiki/Escala_de_Barthel)
        self.EB_BARTHEL_DESCRIPTION = "Index used to measure the success from basic daily life activities (AVDB)."
        # Source: (https://www.murciasalud.es/preevid/1103)
        self.EB_EMINA_DESCRIPTION = "Emina index is a risk valoration tool of developing pressure injuries on hospitalized patients."
        self.EB_SELECT = "Fill the following fields:"
        self.EB_EAT = "Eating"
        self.EB_INDEP = "Independent"
        self.EB_MIN_HELP = "Minimum help"
        self.EB_HELP = "Help needed"
        self.EB_MAX_HELP = "Great help"
        self.EB_WHEEL_HELP = "Independent on wheelchair"
        self.EB_DEP = "Dependent"
        self.EB_WASH = "Cleaning (bath)"
        self.EB_DRESS = "Clothing"
        self.EB_READY = "Getting ready"
        self.EB_DEPO = "Deposition"
        self.EB_CONT = "Continent"
        self.EB_OCC = "Occasional accident"
        self.EB_INCONT = "Uncontinent"
        self.EB_MICC = "Urination"
        self.EB_WC = "Going to WC"
        self.EB_MOVE = "Move (ex: armchair/bed)"
        self.EB_WALK = "Deambulation"
        self.EB_STAIRS = "Up or down stairs."
        self.EB_MENTAL_STATE = "Mental state"
        self.EB_ORIENTED = "Oriented"
        self.EB_DISORIENTED = "Disoriented, apathetic or pasive"
        self.EB_LET = "Lethargic or hyperkinetic"
        self.EB_UNC = "Comatose, unconscient"
        self.EB_MOBILITY = "Mobility"
        self.EB_COMP = "Complete"
        self.EB_LIT_LIM = "Slightly limited"
        self.EB_IMP_LIM = "Important limitation"
        self.EB_IMM = "Immobile"
        self.EB_HUM = "Humidity R/C, Incontinency"
        self.EB_OCC = "Urination or fecal occasionally"
        self.EB_HAB = "Urination or fecal habitual"
        self.EB_BOTH = "Urination and fecal, both"
        self.EB_NUT = "Nutrition"
        self.EB_CORR = "Correct"
        self.EB_OCC_UNC = "Occasionally Incomplete"
        self.EB_UNC = "Incomplete"
        self.EB_NO = "Doesn't ingest"
        self.EB_ACT = "Activity"
        self.EB_DMB = "Wandering"
        self.EB_HLP_DMB = "Wanders with help"
        self.EB_ALWS_HLP= "Always requires help"
        self.EB_NO_DMB = "Doesn't wander"
        self.EB_TXT = "Introduce text"

        #MODEL VIEWER MANAGER
        self.VM_title = "Injury evolution"
        self.VM_id = "Id patient: "
        self.VM_location = "Injury localization: "
        self.VM_cm = "cm"
        self.VM_perimeter_title = "Total perimeter"
        self.VM_perimeter_area = "Total area"
        self.VM_granulation = "Granulation tissue area"
        self.VM_slough = "Slough tissue area"
        self.VM_necrosis = "Necrosis tissue area"

        #VIEW PAGE
        self.VP_CON_DDBB = "Consult database"
        self.VP_PAC_ID = "Id patient: "
        self.VP_LOC = "Localization: "
        self.VP_DATE = "Date: "
        self.VP_EVO = "See evolution"
        self.VP_IMG_LABEL = "<Double click to load an element from the list>"
        self.VP_CODE = "Code: "
        self.VP_GRADE = "Grade: "

        #VIEW SETUP
        self.VS_AT = "Attention"
        self.VS_MSG = "Process finished successfully. Pulse OK to continue."

        #VIEW SEG GUI
        self.SG_WB = "White Balance Correction"
        self.SG_WARNING = "Waring: method is still developing and testing. Please check the result:"
        self.SG_DESC = "Original image // White balanced image"
        self.SG_TITLE = "Confirm region"
        self.SG_CONF = "Is the selected region correct?"
        self.SG_ZONE_TITLE = "Zone type"
        self.SG_ZONE = "Select zone's type:"
        self.SG_RING = "Ring"
        self.SG_CLOSED = "Closed"
        self.SG_PER_EXT = "Outer perimeter"
        self.SG_TISSUE = "Tissue "
        self.SG_SEL_EXT = " : select the region's outer perimeter"
        self.SG_EXT = "Exterior"
        self.SG_PER_INT = "Inner perimeter"
        self.SG_SEL_INT = " : select the region's inner perimeter"
        self.SG_INT = "Inner"
        self.SG_PER_SEL = "Perimeter selected"